In [32]:
import numpy as np
import pandas as pd

In [33]:
data = 'C:/Users/qq/Desktop/football data premier league/DataSet/'
raw_data = []
for year in range(2000, 2018):
    raw_data.append(pd.read_csv(data + str(year) + '.csv',encoding='windows-1252'))
raw_data[17].tail(15)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
365,E0,9/5/2018,Chelsea,Huddersfield,1.0,1.0,D,0.0,0.0,D,...,5.0,2.0,7.0,10.0,9.0,0.0,0.0,1.0,0.0,0.0
366,E0,9/5/2018,Leicester,Arsenal,3.0,1.0,H,1.0,0.0,H,...,10.0,7.0,7.0,12.0,6.0,6.0,2.0,2.0,0.0,1.0
367,E0,9/5/2018,Man City,Brighton,3.0,1.0,H,2.0,1.0,H,...,7.0,3.0,5.0,7.0,4.0,3.0,0.0,1.0,0.0,0.0
368,E0,9/5/2018,Tottenham,Newcastle,1.0,0.0,H,0.0,0.0,D,...,7.0,3.0,10.0,8.0,6.0,4.0,2.0,3.0,0.0,0.0
369,E0,10/5/2018,West Ham,Man United,0.0,0.0,D,0.0,0.0,D,...,2.0,6.0,12.0,12.0,1.0,6.0,1.0,1.0,0.0,0.0
370,NaN,13/5/2018,Burnley,Bournemouth,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
371,NaN,13/5/2018,Crystal Palace,West Brom,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372,NaN,13/5/2018,Huddersfield,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,NaN,13/5/2018,Liverpool,Brighton,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,NaN,13/5/2018,Man United,Watford,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375,NaN,13/5/2018,Newcastle,Chelsea,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,NaN,13/5/2018,Southampton,Man City,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,NaN,13/5/2018,Swansea,Stoke,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,NaN,13/5/2018,Tottenham,Leicester,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,NaN,13/5/2018,West Ham,Everton,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
selected_columns = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR']
seasons = []

In [35]:
for data in raw_data:
    seasons.append(data[selected_columns])

In [36]:
seasons[17].tail()

          Date     HomeTeam   AwayTeam  FTHG  FTAG  FTR
375  13/5/2018    Newcastle    Chelsea   NaN   NaN  NaN
376  13/5/2018  Southampton   Man City   NaN   NaN  NaN
377  13/5/2018      Swansea      Stoke   NaN   NaN  NaN
378  13/5/2018    Tottenham  Leicester   NaN   NaN  NaN
379  13/5/2018     West Ham    Everton   NaN   NaN  NaN

In [37]:
# HTGS - ประตูที่เจ้าบ้านทำได้
# ATGS - ประตูที่ทีมเยือนทำได้

# DataFrame สำหรับประตูที่ทำได้รวมของแต่ละทีม
def get_agg_goals_scored(season):
    # Create  a dictonary 
    teams = {}
    for i in season.groupby('HomeTeam').mean().T.columns: 
        teams[i] = []
    
    # ประตูที่ทำได้ของแต่ละทีมที่ทำได้(เจ้าบ้าน,ทีมเยือน)
    for i in range(len(season)):
        HTGS = season.iloc[i]['FTHG']
        ATGS = season.iloc[i]['FTAG']
        teams[season.iloc[i].HomeTeam].append(HTGS)
        teams[season.iloc[i].AwayTeam].append(ATGS)
        
    # Dataframe สำหรับเก็บประตูที่ทำได้และชื่อทีม
    goals_scored = pd.DataFrame(data=teams, index=[i for i in range(1,(len(season) // 10) + 1)]).T
    goals_scored[0] = 0
    
    # สรุปผลประตูรวมที่ทำได้ของการแข่งขันในแต่ละสัปดาห์
    for i in range(2,(len(season) // 10) + 1):
        goals_scored[i] = goals_scored[i] + goals_scored[i-1]
        
    return goals_scored

In [38]:
 #HTGC - ประตูที่เจ้าบ้านเสียให้คู่แข่ง
# ATGC - ประตูที่ทีมเยือนเสียให้คู่แข่ง

# DataFrame สำหรับประตูที่เสียไปรวมของแต่ละทีม
def get_agg_goals_conceded(season):
    # Create  a dictonary 
    teams = {}
    for i in season.groupby('HomeTeam').mean().T.columns:  # get team name as index
        teams[i] = []
    
     # ประตูที่เสียไปของแต่ละทีมที่ทำได้(เจ้าบ้าน,ทีมเยือน)
    for i in range(len(season)):
        ATGC = season.iloc[i]['FTHG']
        HTGC = season.iloc[i]['FTAG']
        teams[season.iloc[i].HomeTeam].append(HTGC)
        teams[season.iloc[i].AwayTeam].append(ATGC)
        
    # Dataframe สำหรับเก็บประตูที่เสียไปและชื่อทีม
    goals_conceded = pd.DataFrame(data=teams, index=[i for i in range(1,(len(season) // 10) + 1)]).T
    goals_conceded[0] = 0
    
    # สรุปผลประตูรวมที่เสียไปของการแข่งขันในแต่ละสัปดาห์
    for i in range(2,(len(season) // 10) + 1):
        goals_conceded[i] = goals_conceded[i] + goals_conceded[i-1]
        
    return goals_conceded

# สรุปผลประตูรวมของทีมเจ้าบ้านและทีมเยือนใน การแข่งก่อนหน้า

#AHTGS — ประตูรวมเจ้าบ้าน season 2016
#AATGS — ประตูรวมสะสมในฤดูกาลที่ทีมเยือนทำได้ก่อนหน้า
#AHTGC — ประตูรวมสะสมในฤดูกาลที่เจ้าบ้านเสียให้คู่แข่งก่อนหน้า
#AATGC — ประตูรวมสะสมในฤดูกาลที่ทีมเยือนเสียให้คู่แข่งก่อนหน้า

In [39]:
def get_gss(season):
    AGS = get_agg_goals_scored(season)
    AGC = get_agg_goals_conceded(season)
    
    j = 0
    AHTGS = []
    AATGS = []
    AHTGC = []
    AATGC = []
# Filter เฉพาะคอลัมน์ที่มีค่าตามที่เราต้องการโดยใช้ .loc ได้ โดยสามารถเลือก Filter แบบ .all() (ทุกค่าในคอลัมน์ต้องตรงตามเงื่อนไข) หรือ .any() (บางค่าในคอลัมน์ต้องตรงตามเงื่อนไข)   
#นอกจากนี้หากต้องการเข้าถึงข้อมูลโดยอ้างอิงตามลำดับของแถวและลำดับของคอลัมน์ก็สามารถทำได้โดยใช้ .iloc แทน .loc 
# .iloc จะเป็นการเลือกข้อมูลจากตำแหน่งของข้อมูล (เป็นตัวเลข)
#df.iloc[rownum,columnnum]
    for i in range(len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        AHTGS.append(AGS.loc[ht][j])
        AATGS.append(AGS.loc[at][j])
        AHTGC.append(AGC.loc[ht][j])
        AATGC.append(AGC.loc[at][j])
        
        if ((i + 1) % 10) == 0:
            j = j + 1
            
    season['AHTGS'] = AHTGS
    season['AATGS'] = AATGS
    season['AHTGC'] = AHTGC
    season['AATGC'] = AATGC
    
    return season


# Apply to each season
for i, _ in enumerate(seasons):
    seasons[i] = get_gss(seasons[i])

C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [40]:
seasons[17]

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC
0,11/8/2017,Arsenal,Leicester,4.0,3.0,H,0.0,0.0,0.0,0.0
1,12/8/2017,Brighton,Man City,0.0,2.0,A,0.0,0.0,0.0,0.0
2,12/8/2017,Chelsea,Burnley,2.0,3.0,A,0.0,0.0,0.0,0.0
3,12/8/2017,Crystal Palace,Huddersfield,0.0,3.0,A,0.0,0.0,0.0,0.0
4,12/8/2017,Everton,Stoke,1.0,0.0,H,0.0,0.0,0.0,0.0
5,12/8/2017,Southampton,Swansea,0.0,0.0,D,0.0,0.0,0.0,0.0
6,12/8/2017,Watford,Liverpool,3.0,3.0,D,0.0,0.0,0.0,0.0
7,12/8/2017,West Brom,Bournemouth,1.0,0.0,H,0.0,0.0,0.0,0.0
8,13/8/2017,Man United,West Ham,4.0,0.0,H,0.0,0.0,0.0,0.0
9,13/8/2017,Newcastle,Tottenham,0.0,2.0,A,0.0,0.0,0.0,0.0
10,19/8/2017,Bournemouth,Watford,0.0,2.0,A,0.0,3.0,1.0,3.0
11,19/8/2017,Burnley,West Brom,0.0,1.0,A,3.0,1.0,2.0,0.0
12,19/8/2017,Leicester,Brighton,2.0,0.0,H,3.0,0.0,4.0,2.0
13,19/8/2017,Liverpool,Crystal Palace,1.0,0.0,H,3.0,0.0,3.0,3.0
14,19/8/2017,Southampton,West Ham,3.0,2.0,H,0.0,0.0,0.0,4.0
15,19/8/2017,Stoke,Arsenal,1.0,0.0,H,0.0,4.0,1.0,3.0
16,19/8/2017,Swansea,Man United,0.0,4.0,A,0.0,4.0,0.0,0.0
17,20/8/2017,Huddersfield,Newcastle,1.0,0.0,H,3.0,0.0,0.0,2.0
18,20/8/2017,Tottenham,Chelsea,1.0,2.0,A,2.0,2.0,0.0,3.0
19,21/8/2017,Man City,Everton,1.0,1.0,D,2.0,1.0,0.0,0.0
20,26/8/2017,Bournemouth,Man City,1.0,2.0,A,0.0,3.0,3.0,1.0
21,26/8/2017,Crystal Palace,Swansea,0.0,2.0,A,0.0,0.0,4.0,4.0
22,26/8/2017,Huddersfield,Southampton,0.0,0.0,D,4.0,3.0,0.0,2.0
23,26/8/2017,Man United,Leicester,2.0,0.0,H,8.0,5.0,0.0,4.0
24,26/8/2017,Newcastle,West Ham,3.0,0.0,H,0.0,2.0,3.0,7.0
25,26/8/2017,Watford,Brighton,0.0,0.0,D,5.0,0.0,3.0,4.0
26,27/8/2017,Chelsea,Everton,2.0,0.0,H,4.0,2.0,4.0,1.0
27,27/8/2017,Liverpool,Arsenal,4.0,0.0,H,4.0,4.0,3.0,4.0
28,27/8/2017,Tottenham,Burnley,1.0,1.0,D,3.0,3.0,2.0,3.0
29,27/8/2017,West Brom,Stoke,1.0,1.0,D,2.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
350,28/4/2018,Swansea,Chelsea,0.0,1.0,A,27.0,60.0,52.0,34.0
351,29/4/2018,Man United,Arsenal,2.0,1.0,H,67.0,67.0,27.0,48.0
352,29/4/2018,West Ham,Man City,1.0,4.0,A,43.0,102.0,67.0,26.0
353,30/4/2018,Tottenham,Watford,2.0,0.0,H,68.0,42.0,31.0,60.0
354,4/5/2018,Brighton,Man United,1.0,0.0,H,32.0,67.0,47.0,27.0
355,5/5/2018,Bournemouth,Swansea,1.0,0.0,H,41.0,27.0,58.0,52.0
356,5/5/2018,Everton,Southampton,1.0,1.0,D,40.0,35.0,54.0,54.0
357,5/5/2018,Leicester,West Ham,0.0,2.0,A,49.0,43.0,52.0,67.0
358,5/5/2018,Stoke,Crystal Palace,1.0,2.0,A,32.0,36.0,65.0,54.0
359,5/5/2018,Watford,Newcastle,2.0,1.0,H,42.0,35.0,60.0,44.0
360,5/5/2018,West Brom,Tottenham,1.0,0.0,H,30.0,68.0,54.0,32.0
361,6/5/2018,Arsenal,Burnley,5.0,0.0,H,72.0,35.0,48.0,32.0
362,6/5/2018,Chelsea,Liverpool,1.0,0.0,H,61.0,80.0,34.0,37.0
363,6/5/2018,Man City,Huddersfield,0.0,0.0,D,102.0,27.0,26.0,56.0
364,8/5/2018,Swansea,Southampton,0.0,1.0,A,27.0,36.0,53.0,55.0
365,9/5/2018,Chelsea,Huddersfield,1.0,1.0,D,61.0,27.0,34.0,56.0
366,9/5/2018,Leicester,Arsenal,3.0,1.0,H,49.0,72.0,54.0,48.0
367,9/5/2018,Man City,Brighton,3.0,1.0,H,102.0,33.0,26.0,47.0
368,9/5/2018,Tottenham,Newcastle,1.0,0.0,H,68.0,36.0,32.0,46.0
369,10/5/2018,West Ham,Man United,0.0,0.0,D,45.0,67.0,67.0,28.0
370,13/5/2018,Burnley,Bournemouth,NaN,NaN,NaN,35.0,43.0,37.0,60.0
371,13/5/2018,Crystal Palace,West Brom,NaN,NaN,NaN,43.0,31.0,55.0,54.0
372,13/5/2018,Huddersfield,Arsenal,NaN,NaN,NaN,28.0,73.0,57.0,51.0
373,13/5/2018,Liverpool,Brighton,NaN,NaN,NaN,80.0,34.0,38.0,50.0
374,13/5/2018,Man United,Watford,NaN,NaN,NaN,67.0,44.0,28.0,63.0
375,13/5/2018,Newcastle,Chelsea,NaN,NaN,NaN,36.0,62.0,47.0,35.0
376,13/5/2018,Southampton,Man City,NaN,NaN,NaN,37.0,105.0,55.0,27.0
377,13/5/2018,Swansea,Stoke,NaN,NaN,NaN,27.0,33.0,54.0,67.0
378,13/5/2018,Tottenham,Leicester,NaN,NaN,NaN,69.0,52.0,32.0,55.0
379,13/5/2018,West Ham,Everton,NaN,NaN,NaN,45.0,43.0,67.0,55.0

In [41]:
# คำนวนผลจาก FTR ทีมที่ชนะจะได้ 3 คะแนน เสมอได้ 1 คะแนน แพ้ 0 คะแนน
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

In [42]:
def get_cuml_points(match_results, season):
    matchres_points = match_results.applymap(get_points)
    for i in range(2, (len(season) // 10) + 1):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column=0, loc=0, value=[0 * i for i in range(20)])
    return matchres_points

In [43]:
def get_match_results(season):
    # Create dictionary 
    teams = {}
    for i in season.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
        
    # ผลลัพธ์ของการพบกันในแต่ละนัดของฤดูกาลนั้นๆ
    for i in range(len(season)):
        if season.iloc[i].FTR == 'H':
            teams[season.iloc[i].HomeTeam].append('W')
            teams[season.iloc[i].AwayTeam].append('L')
        elif season.iloc[i].FTR == 'A':
            teams[season.iloc[i].HomeTeam].append('L')
            teams[season.iloc[i].AwayTeam].append('W')
        else:
            teams[season.iloc[i].HomeTeam].append('D')
            teams[season.iloc[i].AwayTeam].append('D')
            
    return pd.DataFrame(data=teams, index=[i for i in range(1, (len(season) // 10) + 1)]).T

In [44]:
# HTP — คะแนนรวมที่เจ้าบ้านได้
# ATP — คะแนนรวมที่ทีมเยือนได้

def get_agg_points(season):
    match_results = get_match_results(season)
    cum_pts = get_cuml_points(match_results, season)
    HTP = []
    ATP = []
    j = 0
    for i in range(len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        HTP.append(cum_pts.loc[ht][j])
        ATP.append(cum_pts.loc[at][j])
        
        if ((i + 1) % 10) == 0:
            j = j + 1
            
    season.loc[:,'HTP'] = HTP
    season.loc[:,'ATP'] = ATP
    
    return season

# Apply to each season //enumerate เป็นคำสั่งสำหรับแจกแจงค่า index และข้อมูลใน index ในรูปแบบทูเพิล (Tuple)ดังนี้ (Index,Value) โดยต้องใช้กับข้อมูลชนิด list
for i, _ in enumerate(seasons):
    seasons[i] = get_agg_points(seasons[i])

C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\indexing.py:362: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [45]:
seasons[16]

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC,HTP,ATP
0,13/8/2016,Burnley,Swansea,0,1,A,0,0,0,0,0,0
1,13/8/2016,Crystal Palace,West Brom,0,1,A,0,0,0,0,0,0
2,13/8/2016,Everton,Tottenham,1,1,D,0,0,0,0,0,0
3,13/8/2016,Hull,Leicester,2,1,H,0,0,0,0,0,0
4,13/8/2016,Man City,Sunderland,2,1,H,0,0,0,0,0,0
5,13/8/2016,Middlesbrough,Stoke,1,1,D,0,0,0,0,0,0
6,13/8/2016,Southampton,Watford,1,1,D,0,0,0,0,0,0
7,14/8/2016,Arsenal,Liverpool,3,4,A,0,0,0,0,0,0
8,14/8/2016,Bournemouth,Man United,1,3,A,0,0,0,0,0,0
9,15/8/2016,Chelsea,West Ham,2,1,H,0,0,0,0,0,0
10,19/8/2016,Man United,Southampton,2,0,H,3,1,1,1,3,1
11,20/8/2016,Burnley,Liverpool,2,0,H,0,4,1,3,0,3
12,20/8/2016,Leicester,Arsenal,0,0,D,1,3,2,4,0,0
13,20/8/2016,Stoke,Man City,1,4,A,1,2,1,1,1,3
14,20/8/2016,Swansea,Hull,0,2,A,1,2,0,1,3,3
15,20/8/2016,Tottenham,Crystal Palace,1,0,H,1,0,1,1,1,0
16,20/8/2016,Watford,Chelsea,1,2,A,1,2,1,1,1,3
17,20/8/2016,West Brom,Everton,1,2,A,1,1,0,1,3,1
18,21/8/2016,Sunderland,Middlesbrough,1,2,A,1,1,2,1,0,1
19,21/8/2016,West Ham,Bournemouth,1,0,H,1,1,2,3,0,0
20,27/8/2016,Chelsea,Burnley,3,0,H,4,2,2,1,6,3
21,27/8/2016,Crystal Palace,Bournemouth,1,1,D,0,1,2,4,0,0
22,27/8/2016,Everton,Stoke,1,0,H,3,2,2,5,4,1
23,27/8/2016,Hull,Man United,0,1,A,4,5,1,1,6,6
24,27/8/2016,Leicester,Swansea,2,1,H,1,1,2,2,1,3
25,27/8/2016,Southampton,Sunderland,1,1,D,1,2,3,4,1,0
26,27/8/2016,Tottenham,Liverpool,1,1,D,2,4,1,5,4,3
27,27/8/2016,Watford,Arsenal,1,3,A,2,3,3,4,1,1
28,28/8/2016,Man City,West Ham,3,1,H,6,2,2,2,6,3
29,28/8/2016,West Brom,Middlesbrough,0,0,D,2,3,2,2,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...
350,6/5/2017,Swansea,Everton,1,0,H,40,60,69,40,32,58
351,7/5/2017,Arsenal,Man United,2,0,H,68,51,42,27,66,65
352,7/5/2017,Liverpool,Southampton,0,0,D,71,39,42,46,69,42
353,8/5/2017,Chelsea,Middlesbrough,3,0,H,75,26,29,45,84,28
354,10/5/2017,Southampton,Arsenal,0,2,A,39,68,46,42,42,66
355,12/5/2017,Everton,Watford,1,0,H,60,37,40,58,58,40
356,12/5/2017,West Brom,Chelsea,0,1,A,41,75,45,29,45,84
357,13/5/2017,Bournemouth,Burnley,2,1,H,50,35,63,49,41,39
358,13/5/2017,Man City,Leicester,2,1,H,70,45,37,54,69,43
359,13/5/2017,Middlesbrough,Southampton,1,2,A,26,39,45,46,28,42
360,13/5/2017,Stoke,Arsenal,1,4,A,39,72,52,43,41,69
361,13/5/2017,Sunderland,Swansea,0,2,A,28,41,62,69,24,35
362,14/5/2017,Crystal Palace,Hull,4,0,H,46,36,61,69,38,34
363,14/5/2017,Tottenham,Man United,2,1,H,73,52,24,29,80,65
364,14/5/2017,West Ham,Liverpool,0,4,A,45,71,59,42,42,70
365,15/5/2017,Chelsea,Watford,4,3,H,76,37,29,59,87,40
366,16/5/2017,Arsenal,Sunderland,2,0,H,72,28,43,62,69,24
367,16/5/2017,Man City,West Brom,3,1,H,72,41,38,46,72,45
368,17/5/2017,Southampton,Man United,0,0,D,41,52,47,29,45,65
369,18/5/2017,Leicester,Tottenham,1,6,A,46,73,56,24,43,80
370,21/5/2017,Arsenal,Everton,3,1,H,74,61,43,41,72,61
371,21/5/2017,Burnley,West Ham,1,2,A,38,45,53,63,40,42
372,21/5/2017,Chelsea,Sunderland,5,1,H,80,28,32,64,90,24
373,21/5/2017,Hull,Tottenham,1,7,A,36,79,73,25,34,83
374,21/5/2017,Leicester,Bournemouth,1,1,D,47,54,62,66,43,45
375,21/5/2017,Liverpool,Middlesbrough,3,0,H,75,27,42,50,73,28
376,21/5/2017,Man United,Crystal Palace,2,0,H,52,50,29,61,66,41
377,21/5/2017,Southampton,Stoke,0,1,A,41,40,47,56,46,41
378,21/5/2017,Swansea,West Brom,2,1,H,43,42,69,49,38,45
379,21/5/2017,Watford,Man City,0,5,A,40,75,63,39,40,75

In [46]:
def get_form(season, num):          # the num th before
    form = get_match_results(season)
    form_final = form.copy()
    for i in range(num, (len(season) // 10) + 1):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1
    return form_final

In [47]:
#HM1, HM2, HM3 — ผลการแข็งขันของทีมเจ้าบ้านก่อนหน้า 1, 2, 3 นัด
#AM1, MM2, AM3 — ผลการแข็งขันของทีมเก่อนหน้า 1, 2, 3 นัด

def add_form(season, num):
    form = get_form(season, num)
    h = ['Null' for i in range(num * 10)]    # since form is not available for n MW (n*10)
    a = ['Null' for i in range(num * 10)] #'M'ให้แทนค่าว่าง ใน HM1-3 , AM1-3 ที่ยังไม่ได้มีการเก็บ
    
    j = num
    for i in range((num * 10), len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        
        past = form.loc[ht][j]    # ผลลัพธ์ที่ผ่านมา
        h.append(past[num - 1])   # num- 1 = index ล่าสุด
        
        past = form.loc[at][j]    # ผลลัพธ์ของจำนวน n ที่ผ่านมา
        a.append(past[num - 1])
        
        if ((i + 1) % 10) == 0:
            j = j + 1
            
    season['HM' + str(num)] = h
    season['AM' + str(num)] = a
    
    return season

In [48]:
def add_form_df(season):
    season = add_form(season, 1)
    season = add_form(season, 2)
    season = add_form(season, 3)
    return season

# Apply to each season
for i, _ in enumerate(seasons):
    seasons[i] = add_form_df(seasons[i])

C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [49]:
# จัดเรียงคอลัมน์ใหม่
cols = ['Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'AHTGS', 'AATGS', 'AHTGC', 'AATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3',
        'AM1', 'AM2', 'AM3']

# Apply to each season
for i, _ in enumerate(seasons):
    seasons[i] = seasons[i][cols]

In [50]:
seasons[16]
#อดีต + 1

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC,HTP,ATP,HM1,HM2,HM3,AM1,AM2,AM3
0,13/8/2016,Burnley,Swansea,0,1,A,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
1,13/8/2016,Crystal Palace,West Brom,0,1,A,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
2,13/8/2016,Everton,Tottenham,1,1,D,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
3,13/8/2016,Hull,Leicester,2,1,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
4,13/8/2016,Man City,Sunderland,2,1,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
5,13/8/2016,Middlesbrough,Stoke,1,1,D,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
6,13/8/2016,Southampton,Watford,1,1,D,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
7,14/8/2016,Arsenal,Liverpool,3,4,A,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
8,14/8/2016,Bournemouth,Man United,1,3,A,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
9,15/8/2016,Chelsea,West Ham,2,1,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null
10,19/8/2016,Man United,Southampton,2,0,H,3,1,1,1,3,1,W,Null,Null,D,Null,Null
11,20/8/2016,Burnley,Liverpool,2,0,H,0,4,1,3,0,3,L,Null,Null,W,Null,Null
12,20/8/2016,Leicester,Arsenal,0,0,D,1,3,2,4,0,0,L,Null,Null,L,Null,Null
13,20/8/2016,Stoke,Man City,1,4,A,1,2,1,1,1,3,D,Null,Null,W,Null,Null
14,20/8/2016,Swansea,Hull,0,2,A,1,2,0,1,3,3,W,Null,Null,W,Null,Null
15,20/8/2016,Tottenham,Crystal Palace,1,0,H,1,0,1,1,1,0,D,Null,Null,L,Null,Null
16,20/8/2016,Watford,Chelsea,1,2,A,1,2,1,1,1,3,D,Null,Null,W,Null,Null
17,20/8/2016,West Brom,Everton,1,2,A,1,1,0,1,3,1,W,Null,Null,D,Null,Null
18,21/8/2016,Sunderland,Middlesbrough,1,2,A,1,1,2,1,0,1,L,Null,Null,D,Null,Null
19,21/8/2016,West Ham,Bournemouth,1,0,H,1,1,2,3,0,0,L,Null,Null,L,Null,Null
20,27/8/2016,Chelsea,Burnley,3,0,H,4,2,2,1,6,3,W,W,Null,W,L,Null
21,27/8/2016,Crystal Palace,Bournemouth,1,1,D,0,1,2,4,0,0,L,L,Null,L,L,Null
22,27/8/2016,Everton,Stoke,1,0,H,3,2,2,5,4,1,W,D,Null,L,D,Null
23,27/8/2016,Hull,Man United,0,1,A,4,5,1,1,6,6,W,W,Null,W,W,Null
24,27/8/2016,Leicester,Swansea,2,1,H,1,1,2,2,1,3,D,L,Null,L,W,Null
25,27/8/2016,Southampton,Sunderland,1,1,D,1,2,3,4,1,0,L,D,Null,L,L,Null
26,27/8/2016,Tottenham,Liverpool,1,1,D,2,4,1,5,4,3,W,D,Null,L,W,Null
27,27/8/2016,Watford,Arsenal,1,3,A,2,3,3,4,1,1,L,D,Null,D,L,Null
28,28/8/2016,Man City,West Ham,3,1,H,6,2,2,2,6,3,W,W,Null,W,L,Null
29,28/8/2016,West Brom,Middlesbrough,0,0,D,2,3,2,2,3,4,L,W,Null,W,D,Null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,6/5/2017,Swansea,Everton,1,0,H,40,60,69,40,32,58,D,W,L,L,D,W
351,7/5/2017,Arsenal,Man United,2,0,H,68,51,42,27,66,65,W,W,L,L,D,D
352,7/5/2017,Liverpool,Southampton,0,0,D,71,39,42,46,69,42,W,L,W,L,D,D
353,8/5/2017,Chelsea,Middlesbrough,3,0,H,75,26,29,45,84,28,W,W,W,D,W,L
354,10/5/2017,Southampton,Arsenal,0,2,A,39,68,46,42,42,66,L,D,D,W,W,L
355,12/5/2017,Everton,Watford,1,0,H,60,37,40,58,58,40,L,D,W,L,L,L
356,12/5/2017,West Brom,Chelsea,0,1,A,41,75,45,29,45,84,D,L,L,W,W,W
357,13/5/2017,Bournemouth,Burnley,2,1,H,50,35,63,49,41,39,W,W,L,W,L,L
358,13/5/2017,Man City,Leicester,2,1,H,70,45,37,54,69,43,W,D,D,W,W,L
359,13/5/2017,Middlesbrough,Southampton,1,2,A,26,39,45,46,28,42,D,W,L,L,D,D
360,13/5/2017,Stoke,Arsenal,1,4,A,39,72,52,43,41,69,D,D,L,W,W,W
361,13/5/2017,Sunderland,Swansea,0,2,A,28,41,62,69,24,35,L,W,L,W,D,W
362,14/5/2017,Crystal Palace,Hull,4,0,H,46,36,61,69,38,34,L,L,L,L,D,W
363,14/5/2017,Tottenham,Man United,2,1,H,73,52,24,29,80,65,W,L,W,L,L,D
364,14/5/2017,West Ham,Liverpool,0,4,A,45,71,59,42,42,70,W,D,D,D,W,L
365,15/5/2017,Chelsea,Watford,4,3,H,76,37,29,59,87,40,W,W,W,L,L,L
366,16/5/2017,Arsenal,Sunderland,2,0,H,72,28,43,62,69,24,W,W,W,L,W,L
367,16/5/2017,Man City,West Brom,3,1,H,72,41,38,46,72,45,W,W,D,L,D,L
368,17/5/2017,Southampton,Man United,0,0,D,41,52,47,29,45,65,W,L,D,L,L,D
369,18/5/2017,Leicester,Tottenham,1,6,A,46,73,56,24,43,80,L,W,W,W,L,W
370,21/5/2017,Arsenal,Everton,3,1,H,74,61,43,41,72,61,W,W,W,W,L,L
371,21/5/2017,Burnley,West Ham,1,2,A,38,45,53,63,40,42,L,D,W,L,W,D
372,21/5/2017,Chelsea,Sunderland,5,1,H,80,28,32,64,90,24,W,W,W,L,L,W
373,21/5/2017,Hull,Tottenham,1,7,A,36,79,73,25,34,83,L,L,D,W,W,L
374,21/5/2017,Leicester,Bournemouth,1,1,D,47,54,62,66,43,45,L,L,W,W,D,W
375,21/5/2017,Liverpool,Middlesbrough,3,0,H,75,27,42,50,73,28,W,D,W,L,L,D
376,21/5/2017,Man United,Crystal Palace,2,0,H,52,50,29,61,66,41,D,L,L,W,L,L
377,21/5/2017,Southampton,Stoke,0,1,A,41,40,47,56,46,41,D,W,L,L,D,D
378,21/5/2017,Swansea,West Brom,2,1,H,43,42,69,49,38,45,W,W,D,L,L,D
379,21/5/2017,Watford,Man City,0,5,A,40,75,63,39,40,75,L,L,L,W,W,W

In [51]:
#ใช้ไฟล์ EPLStandings.csv ซึงเป็นข้อมูลอันดับในตารางของแต่ละทีมในฤดูกาลที่ผ่านมา 2000/01–2016/17 โดยจะให้ทีมที่เพิ่งเลื่อนชั้นขึ้นมาจะให้ถือว่าอยู่ในอันดับที่ 18 เมื่อฤดูกาลก่อน (แต่ละฤดูกาลทีมอันดับ 18–20 จะตกชั้น ทีมที่เลื่อนขึ้นมาเลยเปรียบเหมือนอยู่อันดับ 18 เมื่อฤดูกาลก่อน)
#HomeTeamLP- อันดับทีมเจ้าบ้านเมื่อฤดูกาลก่อน
#AwayTeamLP — อันดับทีมเยือนเมื่อฤดูกาลก่อน

standings = pd.read_csv('C:/Users/qq/Desktop/football data premier league/EPLStandings.csv')
standings.set_index(['Team'], inplace=True)
standings = standings.fillna(18)

def get_last(season, standings, year):
    home_team_lp = []
    away_team_lp = []
    for i in range(len(season)):
        ht = season.iloc[i].HomeTeam
        at = season.iloc[i].AwayTeam
        home_team_lp.append(standings.loc[ht][year])
        away_team_lp.append(standings.loc[at][year])
    season['HomeTeamLP'] = home_team_lp
    season['AwayTeamLP'] = away_team_lp
    return season

# Apply to each season
for i, _ in enumerate(seasons):
    seasons[i] = get_last(seasons[i], standings, i)

C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [52]:
seasons[0]

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC,HTP,ATP,HM1,HM2,HM3,AM1,AM2,AM3,HomeTeamLP,AwayTeamLP
0,19/8/2000,Charlton,Man City,4,0,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,18.0,18.0
1,19/8/2000,Chelsea,West Ham,4,2,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,5.0,9.0
2,19/8/2000,Coventry,Middlesbrough,1,3,A,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,14.0,12.0
3,19/8/2000,Derby,Southampton,2,2,D,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,16.0,15.0
4,19/8/2000,Leeds,Everton,2,0,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,3.0,13.0
5,19/8/2000,Leicester,Aston Villa,0,0,D,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,8.0,6.0
6,19/8/2000,Liverpool,Bradford,1,0,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,4.0,17.0
7,19/8/2000,Sunderland,Arsenal,1,0,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,7.0,2.0
8,19/8/2000,Tottenham,Ipswich,3,1,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,10.0,18.0
9,20/8/2000,Man United,Newcastle,2,0,H,0,0,0,0,0,0,Null,Null,Null,Null,Null,Null,1.0,11.0
10,21/8/2000,Arsenal,Liverpool,2,0,H,0,1,1,0,0,3,L,Null,Null,W,Null,Null,2.0,4.0
11,22/8/2000,Bradford,Chelsea,2,0,H,0,4,1,2,0,3,L,Null,Null,W,Null,Null,17.0,5.0
12,22/8/2000,Ipswich,Man United,1,1,D,1,2,3,0,0,3,L,Null,Null,W,Null,Null,18.0,1.0
13,22/8/2000,Middlesbrough,Tottenham,1,1,D,3,3,1,1,3,3,W,Null,Null,W,Null,Null,12.0,10.0
14,23/8/2000,Everton,Charlton,3,0,H,0,4,2,0,0,3,L,Null,Null,W,Null,Null,13.0,18.0
15,23/8/2000,Man City,Sunderland,4,2,H,0,1,4,0,0,3,L,Null,Null,W,Null,Null,18.0,7.0
16,23/8/2000,Newcastle,Derby,3,2,H,0,2,2,2,0,1,L,Null,Null,D,Null,Null,11.0,16.0
17,23/8/2000,Southampton,Coventry,1,2,A,2,1,2,3,1,0,D,Null,Null,L,Null,Null,15.0,14.0
18,23/8/2000,West Ham,Leicester,0,1,A,2,0,4,0,0,1,L,Null,Null,D,Null,Null,9.0,8.0
19,26/8/2000,Arsenal,Charlton,5,3,H,0,4,1,0,0,3,L,Null,Null,W,Null,Null,2.0,18.0
20,26/8/2000,Bradford,Leicester,0,0,D,2,1,1,0,3,4,W,L,Null,W,D,Null,17.0,8.0
21,26/8/2000,Everton,Derby,2,2,D,3,4,2,5,3,1,W,L,Null,L,D,Null,13.0,16.0
22,26/8/2000,Ipswich,Sunderland,1,0,H,2,3,4,4,1,3,D,L,Null,L,W,Null,18.0,7.0
23,26/8/2000,Man City,Coventry,1,2,A,4,3,6,4,3,3,W,L,Null,W,L,Null,18.0,14.0
24,26/8/2000,Middlesbrough,Leeds,1,2,A,4,4,2,1,4,6,D,W,Null,W,W,Null,12.0,3.0
25,26/8/2000,Newcastle,Tottenham,2,0,H,3,4,4,2,3,4,W,L,Null,D,W,Null,11.0,10.0
26,26/8/2000,Southampton,Liverpool,3,3,D,3,1,4,2,1,3,L,D,Null,L,W,Null,15.0,4.0
27,26/8/2000,West Ham,Man United,2,2,D,2,3,5,1,0,4,L,L,Null,D,W,Null,9.0,1.0
28,27/8/2000,Aston Villa,Chelsea,1,1,D,1,4,1,4,2,3,D,D,Null,L,W,Null,6.0,5.0
29,5/9/2000,Leeds,Man City,1,2,A,4,4,1,6,6,3,W,W,Null,W,L,Null,3.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,28/4/2001,Newcastle,Leicester,1,0,H,41,34,47,45,47,45,D,W,D,L,L,L,11.0,8.0
351,28/4/2001,Southampton,Sunderland,0,1,A,35,40,42,37,46,50,D,L,D,D,L,L,15.0,7.0
352,28/4/2001,Tottenham,Aston Villa,0,0,D,42,43,49,38,45,50,L,L,W,D,D,W,10.0,6.0
353,30/4/2001,Charlton,Ipswich,2,1,H,46,53,49,38,49,62,W,D,L,W,W,W,18.0,18.0
354,1/5/2001,Bradford,Liverpool,0,2,A,28,62,63,37,24,62,L,L,W,W,W,W,17.0,4.0
355,1/5/2001,Newcastle,Southampton,1,1,D,41,35,47,42,47,46,D,W,D,D,L,D,11.0,15.0
356,5/5/2001,Arsenal,Leeds,2,1,H,59,54,34,39,66,62,W,W,L,W,W,W,2.0,3.0
357,5/5/2001,Aston Villa,Coventry,3,2,H,43,34,38,58,50,33,D,D,W,L,W,L,6.0,14.0
358,5/5/2001,Bradford,Middlesbrough,1,1,D,28,41,63,40,24,38,L,L,W,W,L,W,17.0,12.0
359,5/5/2001,Chelsea,Everton,2,1,H,62,40,41,54,54,38,L,L,W,L,L,L,5.0,13.0
360,5/5/2001,Leicester,Tottenham,4,2,H,34,42,46,49,45,46,L,L,L,D,L,L,8.0,10.0
361,5/5/2001,Liverpool,Newcastle,3,0,H,65,41,37,50,65,47,W,W,W,L,D,W,4.0,11.0
362,5/5/2001,Man United,Derby,0,1,A,77,35,26,58,80,38,L,W,D,L,L,W,1.0,16.0
363,5/5/2001,Sunderland,Charlton,3,2,H,41,48,37,50,53,52,W,D,L,W,W,D,7.0,18.0
364,5/5/2001,West Ham,Southampton,3,0,H,41,35,48,45,39,46,L,L,L,L,D,L,9.0,15.0
365,7/5/2001,Ipswich,Man City,2,1,H,54,39,40,61,62,34,L,W,W,W,D,W,18.0,18.0
366,8/5/2001,Liverpool,Chelsea,2,2,D,65,64,37,42,65,57,W,W,W,W,L,L,4.0,5.0
367,13/5/2001,Leeds,Bradford,6,1,H,55,29,41,64,62,25,L,W,W,D,L,L,3.0,17.0
368,13/5/2001,Southampton,Man United,2,1,H,35,77,45,26,46,80,L,D,L,L,W,D,15.0,1.0
369,15/5/2001,Newcastle,Arsenal,0,0,D,41,61,50,35,47,69,L,D,W,W,W,W,11.0,2.0
370,19/5/2001,Charlton,Liverpool,0,4,A,50,67,53,39,52,66,L,W,W,D,W,W,18.0,4.0
371,19/5/2001,Coventry,Bradford,0,0,D,36,30,63,70,33,25,L,L,L,L,D,L,14.0,17.0
372,19/5/2001,Derby,Ipswich,1,1,D,36,56,58,41,41,65,W,L,L,W,L,W,16.0,18.0
373,19/5/2001,Everton,Sunderland,2,2,D,43,44,57,39,41,56,L,W,L,W,W,D,13.0,7.0
374,19/5/2001,Leeds,Leicester,3,1,H,61,38,42,48,65,48,W,L,W,W,L,L,3.0,8.0
375,19/5/2001,Man City,Chelsea,1,2,A,40,66,63,44,34,58,L,W,D,D,W,L,18.0,5.0
376,19/5/2001,Middlesbrough,West Ham,2,1,H,42,44,43,48,39,42,D,L,W,W,L,L,12.0,9.0
377,19/5/2001,Newcastle,Aston Villa,3,0,H,41,46,50,40,48,54,D,L,D,W,D,D,11.0,6.0
378,19/5/2001,Southampton,Arsenal,3,2,H,37,61,46,35,49,70,W,L,D,D,W,W,15.0,2.0
379,19/5/2001,Tottenham,Man United,3,1,H,44,78,53,28,46,80,L,D,L,L,L,W,10.0,1.0

In [53]:
def get_mw(season):
    j = 1
    match_week = []
    for i in range(len(season)):
        match_week.append(j)
        if ((i + 1) % 10) == 0:
            j = j + 1
    season['MW'] = match_week
    return season

# Apply to each season
for i, _ in enumerate(seasons):
    seasons[i] = get_mw(seasons[i])

C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [54]:
seasons[0]

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC,...,ATP,HM1,HM2,HM3,AM1,AM2,AM3,HomeTeamLP,AwayTeamLP,MW
0,19/8/2000,Charlton,Man City,4,0,H,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,18.0,18.0,1
1,19/8/2000,Chelsea,West Ham,4,2,H,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,5.0,9.0,1
2,19/8/2000,Coventry,Middlesbrough,1,3,A,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,14.0,12.0,1
3,19/8/2000,Derby,Southampton,2,2,D,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,16.0,15.0,1
4,19/8/2000,Leeds,Everton,2,0,H,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,3.0,13.0,1
5,19/8/2000,Leicester,Aston Villa,0,0,D,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,8.0,6.0,1
6,19/8/2000,Liverpool,Bradford,1,0,H,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,4.0,17.0,1
7,19/8/2000,Sunderland,Arsenal,1,0,H,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,7.0,2.0,1
8,19/8/2000,Tottenham,Ipswich,3,1,H,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,10.0,18.0,1
9,20/8/2000,Man United,Newcastle,2,0,H,0,0,0,0,...,0,Null,Null,Null,Null,Null,Null,1.0,11.0,1
10,21/8/2000,Arsenal,Liverpool,2,0,H,0,1,1,0,...,3,L,Null,Null,W,Null,Null,2.0,4.0,2
11,22/8/2000,Bradford,Chelsea,2,0,H,0,4,1,2,...,3,L,Null,Null,W,Null,Null,17.0,5.0,2
12,22/8/2000,Ipswich,Man United,1,1,D,1,2,3,0,...,3,L,Null,Null,W,Null,Null,18.0,1.0,2
13,22/8/2000,Middlesbrough,Tottenham,1,1,D,3,3,1,1,...,3,W,Null,Null,W,Null,Null,12.0,10.0,2
14,23/8/2000,Everton,Charlton,3,0,H,0,4,2,0,...,3,L,Null,Null,W,Null,Null,13.0,18.0,2
15,23/8/2000,Man City,Sunderland,4,2,H,0,1,4,0,...,3,L,Null,Null,W,Null,Null,18.0,7.0,2
16,23/8/2000,Newcastle,Derby,3,2,H,0,2,2,2,...,1,L,Null,Null,D,Null,Null,11.0,16.0,2
17,23/8/2000,Southampton,Coventry,1,2,A,2,1,2,3,...,0,D,Null,Null,L,Null,Null,15.0,14.0,2
18,23/8/2000,West Ham,Leicester,0,1,A,2,0,4,0,...,1,L,Null,Null,D,Null,Null,9.0,8.0,2
19,26/8/2000,Arsenal,Charlton,5,3,H,0,4,1,0,...,3,L,Null,Null,W,Null,Null,2.0,18.0,2
20,26/8/2000,Bradford,Leicester,0,0,D,2,1,1,0,...,4,W,L,Null,W,D,Null,17.0,8.0,3
21,26/8/2000,Everton,Derby,2,2,D,3,4,2,5,...,1,W,L,Null,L,D,Null,13.0,16.0,3
22,26/8/2000,Ipswich,Sunderland,1,0,H,2,3,4,4,...,3,D,L,Null,L,W,Null,18.0,7.0,3
23,26/8/2000,Man City,Coventry,1,2,A,4,3,6,4,...,3,W,L,Null,W,L,Null,18.0,14.0,3
24,26/8/2000,Middlesbrough,Leeds,1,2,A,4,4,2,1,...,6,D,W,Null,W,W,Null,12.0,3.0,3
25,26/8/2000,Newcastle,Tottenham,2,0,H,3,4,4,2,...,4,W,L,Null,D,W,Null,11.0,10.0,3
26,26/8/2000,Southampton,Liverpool,3,3,D,3,1,4,2,...,3,L,D,Null,L,W,Null,15.0,4.0,3
27,26/8/2000,West Ham,Man United,2,2,D,2,3,5,1,...,4,L,L,Null,D,W,Null,9.0,1.0,3
28,27/8/2000,Aston Villa,Chelsea,1,1,D,1,4,1,4,...,3,D,D,Null,L,W,Null,6.0,5.0,3
29,5/9/2000,Leeds,Man City,1,2,A,4,4,1,6,...,3,W,W,Null,W,L,Null,3.0,18.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,28/4/2001,Newcastle,Leicester,1,0,H,41,34,47,45,...,45,D,W,D,L,L,L,11.0,8.0,36
351,28/4/2001,Southampton,Sunderland,0,1,A,35,40,42,37,...,50,D,L,D,D,L,L,15.0,7.0,36
352,28/4/2001,Tottenham,Aston Villa,0,0,D,42,43,49,38,...,50,L,L,W,D,D,W,10.0,6.0,36
353,30/4/2001,Charlton,Ipswich,2,1,H,46,53,49,38,...,62,W,D,L,W,W,W,18.0,18.0,36
354,1/5/2001,Bradford,Liverpool,0,2,A,28,62,63,37,...,62,L,L,W,W,W,W,17.0,4.0,36
355,1/5/2001,Newcastle,Southampton,1,1,D,41,35,47,42,...,46,D,W,D,D,L,D,11.0,15.0,36
356,5/5/2001,Arsenal,Leeds,2,1,H,59,54,34,39,...,62,W,W,L,W,W,W,2.0,3.0,36
357,5/5/2001,Aston Villa,Coventry,3,2,H,43,34,38,58,...,33,D,D,W,L,W,L,6.0,14.0,36
358,5/5/2001,Bradford,Middlesbrough,1,1,D,28,41,63,40,...,38,L,L,W,W,L,W,17.0,12.0,36
359,5/5/2001,Chelsea,Everton,2,1,H,62,40,41,54,...,38,L,L,W,L,L,L,5.0,13.0,36
360,5/5/2001,Leicester,Tottenham,4,2,H,34,42,46,49,...,46,L,L,L,D,L,L,8.0,10.0,37
361,5/5/2001,Liverpool,Newcastle,3,0,H,65,41,37,50,...,47,W,W,W,L,D,W,4.0,11.0,37
362,5/5/2001,Man United,Derby,0,1,A,77,35,26,58,...,38,L,W,D,L,L,W,1.0,16.0,37
363,5/5/2001,Sunderland,Charlton,3,2,H,41,48,37,50,...,52,W,D,L,W,W,D,7.0,18.0,37
364,5/5/2001,West Ham,Southampton,3,0,H,41,35,48,45,...,46,L,L,L,L,D,L,9.0,15.0,37
365,7/5/2001,Ipswich,Man City,2,1,H,54,39,40,61,...,34,L,W,W,W,D,W,18.0,18.0,37
366,8/5/2001,Liverpool,Chelsea,2,2,D,65,64,37,42,...,57,W,W,W,W,L,L,4.0,5.0,37
367,13/5/2001,Leeds,Bradford,6,1,H,55,29,41,64,...,25,L,W,W,D,L,L,3.0,17.0,37
368,13/5/2001,Southampton,Man United,2,1,H,35,77,45,26,...,80,L,D,L,L,W,D,15.0,1.0,37
369,15/5/2001,Newcastle,Arsenal,0,0,D,41,61,50,35,...,69,L,D,W,W,W,W,11.0,2.0,37
370,19/5/2001,Charlton,Liverpool,0,4,A,50,67,53,39,...,66,L,W,W,D,W,W,18.0,4.0,38
371,19/5/2001,Coventry,Bradford,0,0,D,36,30,63,70,...,25,L,L,L,L,D,L,14.0,17.0,38
372,19/5/2001,Derby,Ipswich,1,1,D,36,56,58,41,...,65,W,L,L,W,L,W,16.0,18.0,38
373,19/5/2001,Everton,Sunderland,2,2,D,43,44,57,39,...,56,L,W,L,W,W,D,13.0,7.0,38
374,19/5/2001,Leeds,Leicester,3,1,H,61,38,42,48,...,48,W,L,W,W,L,L,3.0,8.0,38
375,19/5/2001,Man City,Chelsea,1,2,A,40,66,63,44,...,58,L,W,D,D,W,L,18.0,5.0,38
376,19/5/2001,Middlesbrough,West Ham,2,1,H,42,44,43,48,...,42,D,L,W,W,L,L,12.0,9.0,38
377,19/5/2001,Newcastle,Aston Villa,3,0,H,41,46,50,40,...,54,D,L,D,W,D,D,11.0,6.0,38
378,19/5/2001,Southampton,Arsenal,3,2,H,37,61,46,35,...,70,W,L,D,D,W,W,15.0,2.0,38
379,19/5/2001,Tottenham,Man United,3,1,H,44,78,53,28,...,80,L,D,L,L,L,W,10.0,1.0,38

In [55]:
#รวมไฟล์ แล้วตั้ง index ให้ต่อเนื่องกัน 0-6300...
gameplays = pd.concat(seasons, ignore_index=True)

In [56]:
gameplays

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC,...,ATP,HM1,HM2,HM3,AM1,AM2,AM3,HomeTeamLP,AwayTeamLP,MW
0,19/8/2000,Charlton,Man City,4.0,0.0,H,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,18.0,18.0,1
1,19/8/2000,Chelsea,West Ham,4.0,2.0,H,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,5.0,9.0,1
2,19/8/2000,Coventry,Middlesbrough,1.0,3.0,A,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,14.0,12.0,1
3,19/8/2000,Derby,Southampton,2.0,2.0,D,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,16.0,15.0,1
4,19/8/2000,Leeds,Everton,2.0,0.0,H,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,3.0,13.0,1
5,19/8/2000,Leicester,Aston Villa,0.0,0.0,D,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,8.0,6.0,1
6,19/8/2000,Liverpool,Bradford,1.0,0.0,H,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,4.0,17.0,1
7,19/8/2000,Sunderland,Arsenal,1.0,0.0,H,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,7.0,2.0,1
8,19/8/2000,Tottenham,Ipswich,3.0,1.0,H,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,10.0,18.0,1
9,20/8/2000,Man United,Newcastle,2.0,0.0,H,0.0,0.0,0.0,0.0,...,0,Null,Null,Null,Null,Null,Null,1.0,11.0,1
10,21/8/2000,Arsenal,Liverpool,2.0,0.0,H,0.0,1.0,1.0,0.0,...,3,L,Null,Null,W,Null,Null,2.0,4.0,2
11,22/8/2000,Bradford,Chelsea,2.0,0.0,H,0.0,4.0,1.0,2.0,...,3,L,Null,Null,W,Null,Null,17.0,5.0,2
12,22/8/2000,Ipswich,Man United,1.0,1.0,D,1.0,2.0,3.0,0.0,...,3,L,Null,Null,W,Null,Null,18.0,1.0,2
13,22/8/2000,Middlesbrough,Tottenham,1.0,1.0,D,3.0,3.0,1.0,1.0,...,3,W,Null,Null,W,Null,Null,12.0,10.0,2
14,23/8/2000,Everton,Charlton,3.0,0.0,H,0.0,4.0,2.0,0.0,...,3,L,Null,Null,W,Null,Null,13.0,18.0,2
15,23/8/2000,Man City,Sunderland,4.0,2.0,H,0.0,1.0,4.0,0.0,...,3,L,Null,Null,W,Null,Null,18.0,7.0,2
16,23/8/2000,Newcastle,Derby,3.0,2.0,H,0.0,2.0,2.0,2.0,...,1,L,Null,Null,D,Null,Null,11.0,16.0,2
17,23/8/2000,Southampton,Coventry,1.0,2.0,A,2.0,1.0,2.0,3.0,...,0,D,Null,Null,L,Null,Null,15.0,14.0,2
18,23/8/2000,West Ham,Leicester,0.0,1.0,A,2.0,0.0,4.0,0.0,...,1,L,Null,Null,D,Null,Null,9.0,8.0,2
19,26/8/2000,Arsenal,Charlton,5.0,3.0,H,0.0,4.0,1.0,0.0,...,3,L,Null,Null,W,Null,Null,2.0,18.0,2
20,26/8/2000,Bradford,Leicester,0.0,0.0,D,2.0,1.0,1.0,0.0,...,4,W,L,Null,W,D,Null,17.0,8.0,3
21,26/8/2000,Everton,Derby,2.0,2.0,D,3.0,4.0,2.0,5.0,...,1,W,L,Null,L,D,Null,13.0,16.0,3
22,26/8/2000,Ipswich,Sunderland,1.0,0.0,H,2.0,3.0,4.0,4.0,...,3,D,L,Null,L,W,Null,18.0,7.0,3
23,26/8/2000,Man City,Coventry,1.0,2.0,A,4.0,3.0,6.0,4.0,...,3,W,L,Null,W,L,Null,18.0,14.0,3
24,26/8/2000,Middlesbrough,Leeds,1.0,2.0,A,4.0,4.0,2.0,1.0,...,6,D,W,Null,W,W,Null,12.0,3.0,3
25,26/8/2000,Newcastle,Tottenham,2.0,0.0,H,3.0,4.0,4.0,2.0,...,4,W,L,Null,D,W,Null,11.0,10.0,3
26,26/8/2000,Southampton,Liverpool,3.0,3.0,D,3.0,1.0,4.0,2.0,...,3,L,D,Null,L,W,Null,15.0,4.0,3
27,26/8/2000,West Ham,Man United,2.0,2.0,D,2.0,3.0,5.0,1.0,...,4,L,L,Null,D,W,Null,9.0,1.0,3
28,27/8/2000,Aston Villa,Chelsea,1.0,1.0,D,1.0,4.0,1.0,4.0,...,3,D,D,Null,L,W,Null,6.0,5.0,3
29,5/9/2000,Leeds,Man City,1.0,2.0,A,4.0,4.0,1.0,6.0,...,3,W,W,Null,W,L,Null,3.0,18.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6810,28/4/2018,Swansea,Chelsea,0.0,1.0,A,27.0,60.0,52.0,34.0,...,66,L,L,D,W,W,W,15.0,1.0,36
6811,29/4/2018,Man United,Arsenal,2.0,1.0,H,67.0,67.0,27.0,48.0,...,57,W,W,L,L,W,L,6.0,5.0,36
6812,29/4/2018,West Ham,Man City,1.0,4.0,A,43.0,102.0,67.0,26.0,...,93,L,L,D,W,W,W,11.0,3.0,36
6813,30/4/2018,Tottenham,Watford,2.0,0.0,H,68.0,42.0,31.0,60.0,...,38,W,D,L,D,L,L,2.0,17.0,36
6814,4/5/2018,Brighton,Man United,1.0,0.0,H,32.0,67.0,47.0,27.0,...,77,D,D,L,W,W,L,18.0,6.0,36
6815,5/5/2018,Bournemouth,Swansea,1.0,0.0,H,41.0,27.0,58.0,52.0,...,33,L,L,D,L,L,D,9.0,15.0,36
6816,5/5/2018,Everton,Southampton,1.0,1.0,D,40.0,35.0,54.0,54.0,...,32,W,D,D,W,D,L,7.0,8.0,36
6817,5/5/2018,Leicester,West Ham,0.0,2.0,A,49.0,43.0,52.0,67.0,...,35,L,D,L,L,L,D,12.0,11.0,36
6818,5/5/2018,Stoke,Crystal Palace,1.0,2.0,A,32.0,36.0,65.0,54.0,...,35,D,D,L,D,W,D,13.0,14.0,36
6819,5/5/2018,Watford,Newcastle,2.0,1.0,H,42.0,35.0,60.0,44.0,...,41,D,L,L,L,L,W,17.0,18.0,36
6820,5/5/2018,West Brom,Tottenham,1.0,0.0,H,30.0,68.0,54.0,32.0,...,71,W,D,W,L,W,D,10.0,2.0,37
6821,6/5/2018,Arsenal,Burnley,5.0,0.0,H,72.0,35.0,48.0,32.0,...,54,W,L,W,D,D,L,5.0,16.0,37
6822,6/5/2018,Chelsea,Liverpool,1.0,0.0,H,61.0,80.0,34.0,37.0,...,72,W,W,W,D,D,W,1.0,4.0,37
6823,6/5/2018,Man City,Huddersfield,0.0,0.0,D,102.0,27.0,26.0,56.0,...,36,D,W,W,D,L,W,3.0,18.0,37
6824,8/5/2018,Swansea,Southampton,0.0,1.0,A,27.0,36.0,53.0,55.0,...,33,L,L,L,D,W,D,15.0,8.0,37
6825,9/5/2018,Chelsea,Huddersfield,1.0,1.0,D,61.0,27.0,34.0,56.0,...,36,W,W,W,D,L,W,1.0,18.0,37
6826,9/5/2018,Leicester,Arsenal,3.0,1.0,H,49.0,72.0,54.0,48.0,...,60,L,L,D,W,L,W,12.0,5.0,37
6827,9/5/2018,Man City,Brighton,3.0,1.0,H,102.0,33.0,26.0,47.0,...,40,D,W,W,W,D,D,3.0,18.0,37
6828,9/5/2018,Tottenham,Newcastle,1.0,0.0,H,68.0,36.0,32.0,46.0,...,41,L,W,D,L,L,L,2.0,18.0,37
6829,10/5/2018,West Ham,Man United,0.0,0.0,D,45.0,67.0,67.0,28.0,...,77,W,L,L,L,W,W,11.0,6.0,37
6830,13/5/2018,Burnley,Bournemouth,NaN,NaN,NaN,35.0,43.0,37.0,60.0,...,41,L,D,D,W,L,L,16.0,9.0,38
6831,13/5/2018,Crystal Palace,West Brom,NaN,NaN,NaN,43.0,31.0,55.0,54.0,...,31,W,W,D,W,W,D,14.0,10.0,38
6832,13/5/2018,Huddersfield,Arsenal,NaN,NaN,NaN,28.0,73.0,57.0,51.0,...,60,D,D,L,L,W,L,18.0,5.0,38
6833,13/5/2018,Liverpool,Brighton,NaN,NaN,NaN,80.0,34.0,38.0,50.0,...,40,L,D,D,L,W,D,4.0,18.0,38
6834,13/5/2018,Man United,Watford,NaN,NaN,NaN,67.0,44.0,28.0,63.0,...,41,D,L,W,W,L,D,6.0,17.0,38
6835,13/5/2018,Newcastle,Chelsea,NaN,NaN,NaN,36.0,62.0,47.0,35.0,...,70,L,L,L,D,W,W,18.0,1.0,38
6836,13/5/2018,Southampton,Man City,NaN,NaN,NaN,37.0,105.0,55.0,27.0,...,97,W,D,W,W,D,W,8.0,3.0,38
6837,13/5/2018,Swansea,Stoke,NaN,NaN,NaN,27.0,33.0,54.0,67.0,...,30,L,L,L,L,D,D,15.0,13.0,38
6838,13/5/2018,Tottenham,Leicester,NaN,NaN,NaN,69.0,52.0,32.0,55.0,...,47,W,L,W,W,L,L,2.0,12.0,38
6839,13/5/2018,West Ham,Everton,NaN,NaN,NaN,45.0,43.0,67.0,55.0,...,49,D,W,L,D,W,W,11.0,7.0,38

In [57]:
# DiffLP — ส่วนต่างลำดับทีมในตาราง
gameplays['DiffLP'] = gameplays['HomeTeamLP'] - gameplays['AwayTeamLP']

In [58]:

#HTGD — ส่วนต่างประตูได้เสียของทีมเจ้าบ้าน
#ATGD — ส่วนต่างประตูได้เสียของทีมเยือน

gameplays['HTGD'] = gameplays['AHTGS'] - gameplays['AHTGC']
gameplays['ATGD'] = gameplays['AATGS'] - gameplays['AATGC']

In [59]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

gameplays['HTFormPtsStr'] = gameplays['HM1'] + gameplays['HM2'] + gameplays['HM3']
gameplays['ATFormPtsStr'] = gameplays['AM1'] + gameplays['AM2'] + gameplays['AM3']

gameplays['HTFormPts'] = gameplays['HTFormPtsStr'].apply(get_form_points)
gameplays['ATFormPts'] = gameplays['ATFormPtsStr'].apply(get_form_points)

# DiffFormPts —ส่วนต่างคะแนน (HTP - ATP) คิดจากคะแนนที่ทำได้จากฟอร์ม 3 หลังสุดของแต่ละทีม แล้วคำนวนความต่างของแต่ละคู่
gameplays['DiffFormPts'] = gameplays['HTFormPts'] - gameplays['ATFormPts']

In [60]:
gameplays.tail()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC,...,AwayTeamLP,MW,DiffLP,HTGD,ATGD,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,DiffFormPts
6835,13/5/2018,Newcastle,Chelsea,NaN,NaN,NaN,36.0,62.0,47.0,35.0,...,1.0,38,17.0,-11.0,27.0,LLL,DWW,0,7,-7
6836,13/5/2018,Southampton,Man City,NaN,NaN,NaN,37.0,105.0,55.0,27.0,...,3.0,38,5.0,-18.0,78.0,WDW,WDW,7,7,0
6837,13/5/2018,Swansea,Stoke,NaN,NaN,NaN,27.0,33.0,54.0,67.0,...,13.0,38,2.0,-27.0,-34.0,LLL,LDD,0,2,-2
6838,13/5/2018,Tottenham,Leicester,NaN,NaN,NaN,69.0,52.0,32.0,55.0,...,12.0,38,-10.0,37.0,-3.0,WLW,WLL,6,3,3
6839,13/5/2018,West Ham,Everton,NaN,NaN,NaN,45.0,43.0,67.0,55.0,...,7.0,38,4.0,-22.0,-12.0,DWL,DWW,4,7,-3

In [61]:
#  scale ค่า HTP, ATP, HTGD, ATGD, DiffFormPts ด้วย MW หรือทำการเฉลี่ยค่าต่อเกม
cols = ['HTP','ATP','HTGD','ATGD','DiffFormPts']
gameplays.MW = gameplays.MW.astype(float)

for col in cols:
    gameplays[col] = gameplays[col] / gameplays.MW

gameplays.tail(30)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AHTGS,AATGS,AHTGC,AATGC,...,AwayTeamLP,MW,DiffLP,HTGD,ATGD,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,DiffFormPts
6810,28/4/2018,Swansea,Chelsea,0.0,1.0,A,27.0,60.0,52.0,34.0,...,1.0,36.0,14.0,-0.694444,0.722222,LLD,WWW,1,9,-0.222222
6811,29/4/2018,Man United,Arsenal,2.0,1.0,H,67.0,67.0,27.0,48.0,...,5.0,36.0,1.0,1.111111,0.527778,WWL,LWL,6,3,0.083333
6812,29/4/2018,West Ham,Man City,1.0,4.0,A,43.0,102.0,67.0,26.0,...,3.0,36.0,8.0,-0.666667,2.111111,LLD,WWW,1,9,-0.222222
6813,30/4/2018,Tottenham,Watford,2.0,0.0,H,68.0,42.0,31.0,60.0,...,17.0,36.0,-15.0,1.027778,-0.500000,WDL,DLL,4,1,0.083333
6814,4/5/2018,Brighton,Man United,1.0,0.0,H,32.0,67.0,47.0,27.0,...,6.0,36.0,12.0,-0.416667,1.111111,DDL,WWL,2,6,-0.111111
6815,5/5/2018,Bournemouth,Swansea,1.0,0.0,H,41.0,27.0,58.0,52.0,...,15.0,36.0,-6.0,-0.472222,-0.694444,LLD,LLD,1,1,0.000000
6816,5/5/2018,Everton,Southampton,1.0,1.0,D,40.0,35.0,54.0,54.0,...,8.0,36.0,-1.0,-0.388889,-0.527778,WDD,WDL,5,4,0.027778
6817,5/5/2018,Leicester,West Ham,0.0,2.0,A,49.0,43.0,52.0,67.0,...,11.0,36.0,1.0,-0.083333,-0.666667,LDL,LLD,1,1,0.000000
6818,5/5/2018,Stoke,Crystal Palace,1.0,2.0,A,32.0,36.0,65.0,54.0,...,14.0,36.0,-1.0,-0.916667,-0.500000,DDL,DWD,2,5,-0.083333
6819,5/5/2018,Watford,Newcastle,2.0,1.0,H,42.0,35.0,60.0,44.0,...,18.0,36.0,-1.0,-0.500000,-0.250000,DLL,LLW,1,3,-0.055556
6820,5/5/2018,West Brom,Tottenham,1.0,0.0,H,30.0,68.0,54.0,32.0,...,2.0,37.0,8.0,-0.648649,0.972973,WDW,LWD,7,4,0.081081
6821,6/5/2018,Arsenal,Burnley,5.0,0.0,H,72.0,35.0,48.0,32.0,...,16.0,37.0,-11.0,0.648649,0.081081,WLW,DDL,6,2,0.108108
6822,6/5/2018,Chelsea,Liverpool,1.0,0.0,H,61.0,80.0,34.0,37.0,...,4.0,37.0,-3.0,0.729730,1.162162,WWW,DDW,9,5,0.108108
6823,6/5/2018,Man City,Huddersfield,0.0,0.0,D,102.0,27.0,26.0,56.0,...,18.0,37.0,-15.0,2.054054,-0.783784,DWW,DLW,7,4,0.081081
6824,8/5/2018,Swansea,Southampton,0.0,1.0,A,27.0,36.0,53.0,55.0,...,8.0,37.0,7.0,-0.702703,-0.513514,LLL,DWD,0,5,-0.135135
6825,9/5/2018,Chelsea,Huddersfield,1.0,1.0,D,61.0,27.0,34.0,56.0,...,18.0,37.0,-17.0,0.729730,-0.783784,WWW,DLW,9,4,0.135135
6826,9/5/2018,Leicester,Arsenal,3.0,1.0,H,49.0,72.0,54.0,48.0,...,5.0,37.0,7.0,-0.135135,0.648649,LLD,WLW,1,6,-0.135135
6827,9/5/2018,Man City,Brighton,3.0,1.0,H,102.0,33.0,26.0,47.0,...,18.0,37.0,-15.0,2.054054,-0.378378,DWW,WDD,7,5,0.054054
6828,9/5/2018,Tottenham,Newcastle,1.0,0.0,H,68.0,36.0,32.0,46.0,...,18.0,37.0,-16.0,0.972973,-0.270270,LWD,LLL,4,0,0.108108
6829,10/5/2018,West Ham,Man United,0.0,0.0,D,45.0,67.0,67.0,28.0,...,6.0,37.0,5.0,-0.594595,1.054054,WLL,LWW,3,6,-0.081081
6830,13/5/2018,Burnley,Bournemouth,NaN,NaN,NaN,35.0,43.0,37.0,60.0,...,9.0,38.0,7.0,-0.052632,-0.447368,LDD,WLL,2,3,-0.026316
6831,13/5/2018,Crystal Palace,West Brom,NaN,NaN,NaN,43.0,31.0,55.0,54.0,...,10.0,38.0,4.0,-0.315789,-0.605263,WWD,WWD,7,7,0.000000
6832,13/5/2018,Huddersfield,Arsenal,NaN,NaN,NaN,28.0,73.0,57.0,51.0,...,5.0,38.0,13.0,-0.763158,0.578947,DDL,LWL,2,3,-0.026316
6833,13/5/2018,Liverpool,Brighton,NaN,NaN,NaN,80.0,34.0,38.0,50.0,...,18.0,38.0,-14.0,1.105263,-0.421053,LDD,LWD,2,4,-0.052632
6834,13/5/2018,Man United,Watford,NaN,NaN,NaN,67.0,44.0,28.0,63.0,...,17.0,38.0,-11.0,1.026316,-0.500000,DLW,WLD,4,4,0.000000
6835,13/5/2018,Newcastle,Chelsea,NaN,NaN,NaN,36.0,62.0,47.0,35.0,...,1.0,38.0,17.0,-0.289474,0.710526,LLL,DWW,0,7,-0.184211
6836,13/5/2018,Southampton,Man City,NaN,NaN,NaN,37.0,105.0,55.0,27.0,...,3.0,38.0,5.0,-0.473684,2.052632,WDW,WDW,7,7,0.000000
6837,13/5/2018,Swansea,Stoke,NaN,NaN,NaN,27.0,33.0,54.0,67.0,...,13.0,38.0,2.0,-0.710526,-0.894737,LLL,LDD,0,2,-0.052632
6838,13/5/2018,Tottenham,Leicester,NaN,NaN,NaN,69.0,52.0,32.0,55.0,...,12.0,38.0,-10.0,0.973684,-0.078947,WLW,WLL,6,3,0.078947
6839,13/5/2018,West Ham,Everton,NaN,NaN,NaN,45.0,43.0,67.0,55.0,...,7.0,38.0,4.0,-0.578947,-0.315789,DWL,DWW,4,7,-0.078947

In [62]:
gameplays.to_csv('C:/Users/qq/Desktop/football data premier league/final_dataset.csv')